package com.aurelia.loaning.event;

public enum Event {

	SHOW_LOANINGS, //
	SHOW_LOANINGS_HISTORY, //
	SAVE_LOANING, //
	DELETE_LOAN, //
	SETTLE_LOAN, //
	DELETE_ALL_FILTERED_LOANS, //
	SETTLE_ALL_FILTERED_LOANS, //
	LOAN_MODIFIED, //
	DISPLAY_LOAN_DETAIL, //
	UPDATE_LOAN, REMOVE_NOTIFICATION;

}
