package com.aurelia.loaning.event;

public enum Event {

	BOOT_COMPLETED, //
	PERIODIC_NOTIFICATION_CHECK, //
	PERIODIC_NOTIFICATION_CHECK_RESULT, //
	APPLICATION_STARTUP, //
	APPLICATION_STARTUP_RESULT, //
	SHOW_LOANINGS, //
	LIST_ELAPSED_LOANS, //
	SHOW_LOANINGS_HISTORY, //
	SAVE_LOANING, //
	DELETE_LOAN, //
	SETTLE_LOAN, //
	DELETE_ALL_FILTERED_LOANS, //
	SETTLE_ALL_FILTERED_LOANS, //
	LOAN_MODIFIED, //
	DISPLAY_LOAN_DETAIL, //
	UPDATE_LOAN, //
	SEND_ELAPSED_LOANS, //
	REMOVE_NOTIFICATION;

}
